# Site settings
title: "Kurau's Blog"
name: "Kuraus >_<"
email: "kurau@gmail.com"
description: >
    Что здесь? Кто здесь?
baseurl: ""
url: "http://kurau.github.io"
twitter_username: "kuraushka"
github_username: "kurau"
disqus_username: "kurau-github-io"

google-analytics: # add it if you have one

skillstree: false # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
