# Site settings
title: "1234"
name: "Kuraus >_<" # your name
email: "kurau@gmail.com" # your email address
description: >
    Что здесь? Кто здесь?
baseurl: ""
url: "http://kurau.github.io" # the base hostname & protocol for your site
twitter_username: "kuraushka"
github_username: "kurau"
disqus_username: "kurau"

google-analytics: # add it if you have one

skillstree: false # turn on or off the skills tree in about page

# Build settings
permalink: none
markdown: kramdown
